[pytest]
addopts = -ra
pythonpath = .
filterwarnings =
    ignore:pkg_resources is deprecated as an API:DeprecationWarning
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('snowflake'\)`:DeprecationWarning
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('sphinxcontrib'\)`:DeprecationWarning



