"""
Duration Efficiency Models Package.

Exports data models and configuration for duration efficiency analysis.
"""

from .config import (
    BREAK_CLUSTER_WINDOW_HOURS,
    CONFIDENCE_LEVEL,
    IQR_MULTIPLIER,
    MIN_SAMPLE_SIZE,
    MIN_SESSIONS_FOR_ANALYSIS,
    MIN_SESSIONS_FOR_SHIFT_REPORT,
    MIN_SHOTS_PER_SESSION,
    MIN_TOOLS_FOR_CONSISTENCY,
    PLANNED_DOWNTIME_CV_THRESHOLD,
    PLANNED_DOWNTIME_MIN_RATIO,
    PRODUCTION_END_BREAK_HOURS,
    SEVERITY_LEVELS,
    TIER_CLASSIFICATIONS,
    TIER_COLORS,
    WARMUP_SHOT_COUNT,
    Z_SCORE_THRESHOLD,
    DataQualityIssue,
    EfficiencyMetrics,
    OperatorBenchmark,
    OperatorShiftPattern,
    SupplierBenchmark,
    classify_supplier_tier,
    get_default_config,
    get_severity_weight,
    get_tier_color,
)

__all__ = [
    "DataQualityIssue",
    "EfficiencyMetrics",
    "SupplierBenchmark",
    "OperatorShiftPattern",
    "OperatorBenchmark",
    "get_default_config",
    "classify_supplier_tier",
    "get_severity_weight",
    "get_tier_color",
    "SEVERITY_LEVELS",
    "TIER_CLASSIFICATIONS",
    "TIER_COLORS",
    "Z_SCORE_THRESHOLD",
    "IQR_MULTIPLIER",
    "CONFIDENCE_LEVEL",
    "MIN_SAMPLE_SIZE",
    "MIN_TOOLS_FOR_CONSISTENCY",
    "PRODUCTION_END_BREAK_HOURS",
    "WARMUP_SHOT_COUNT",
    "PLANNED_DOWNTIME_CV_THRESHOLD",
    "MIN_SESSIONS_FOR_ANALYSIS",
    "MIN_SESSIONS_FOR_SHIFT_REPORT",
    "MIN_SHOTS_PER_SESSION",
    "PLANNED_DOWNTIME_MIN_RATIO",
    "BREAK_CLUSTER_WINDOW_HOURS",
]
